package com.wilddeck.engine;

public enum ContractActionType {
    HOSTILE_DIRECT,
    HOSTILE_PROXY,
    HOSTILE_COOPERATION,
    DISCLOSE_ALLIANCE,
    DEFENSIVE_SUPPORT,
    SHARE_CONFIRMED_THREAT,

    INVESTIGATE_INFORMATION,
    SPY_INFORMATION,
    QUESTION_OTHERS,
    DISCLOSE_INFORMATION,
    TRADE_INFORMATION,
    SPREAD_INFORMATION,
    DISCUSS_INFORMATION
}
